@pip install tkinter
@pip install subprocess
@pip install pyperclip
@pip install requests
@pip install time
@pip install sys
@pip install mmh3
@pip install chardet
@pip install re
@pip install sqlite3
@pip install codecs
@pip install base64
@pip install random
@pip install os
@pip install shodan